# Generated by Django 4.2.9 on 2026-05-22 10:44

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20)),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ProjectCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_costs', to='core.company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='projects.project')),
            ],
            options={
                'ordering': ['-cost_date'],
            },
        ),
    ]
