# Generated by Django 4.2.9 on 2026-06-15 08:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoicing', '0002_alter_invoice_invoice_number_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('INVOICE', 'Invoice'), ('PAYMENT_REMINDER', 'Payment Reminder'), ('RECEIPT', 'Receipt'), ('STATEMENT', 'Statement'), ('MARKETING', 'Marketing')], max_length=50)),
                ('language', models.CharField(default='en', max_length=10)),
                ('content', models.TextField(help_text='Use {{variable_name}} for dynamic content')),
                ('variables', models.JSONField(default=list, help_text='List of variable names used in template')),
                ('whatsapp_template_id', models.CharField(blank=True, max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_templates', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number_id', models.CharField(max_length=100)),
                ('business_account_id', models.CharField(blank=True, max_length=100)),
                ('access_token', models.CharField(max_length=500)),
                ('webhook_verify_token', models.CharField(blank=True, max_length=100)),
                ('webhook_url', models.URLField(blank=True)),
                ('invoice_template_name', models.CharField(default='invoice_payment', max_length=100)),
                ('reminder_template_name', models.CharField(default='payment_reminder', max_length=100)),
                ('receipt_template_name', models.CharField(default='payment_receipt', max_length=100)),
                ('auto_send_invoice', models.BooleanField(default=False)),
                ('auto_send_reminders', models.BooleanField(default=False)),
                ('reminder_days_before_due', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_config', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('message_type', models.CharField(choices=[('TEXT', 'Text'), ('DOCUMENT', 'Document'), ('TEMPLATE', 'Template'), ('INTERACTIVE', 'Interactive')], max_length=50)),
                ('content', models.TextField()),
                ('media_url', models.URLField(blank=True)),
                ('direction', models.CharField(choices=[('OUTBOUND', 'Outbound'), ('INBOUND', 'Inbound')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('message_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('conversation_id', models.CharField(blank=True, max_length=100)),
                ('error_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('raw_request', models.JSONField(blank=True, default=dict)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='core.company')),
                ('linked_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.customer')),
                ('linked_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number'], name='whatsapp_wh_phone_n_9c2c66_idx'), models.Index(fields=['status'], name='whatsapp_wh_status_55e250_idx'), models.Index(fields=['created_at'], name='whatsapp_wh_created_e0ca2a_idx')],
            },
        ),
    ]
