# Generated by Django 4.2.9 on 2026-06-15 08:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaSTKPush',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('account_reference', models.CharField(max_length=50)),
                ('transaction_description', models.CharField(max_length=100)),
                ('checkout_request_id', models.CharField(max_length=100, unique=True)),
                ('merchant_request_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('TIMEOUT', 'Timeout'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=50)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_desc', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stk_pushes', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='MpesaConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_shortcode', models.CharField(help_text='M-Pesa Paybill or Till Number', max_length=20)),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('PAYBILL', 'Paybill'), ('TILL', 'Till Number')], max_length=20)),
                ('consumer_key', models.CharField(blank=True, max_length=100)),
                ('consumer_secret', models.CharField(blank=True, max_length=100)),
                ('passkey', models.CharField(blank=True, max_length=100)),
                ('environment', models.CharField(choices=[('SANDBOX', 'Sandbox'), ('PRODUCTION', 'Production')], default='SANDBOX', max_length=20)),
                ('confirmation_url', models.URLField(blank=True)),
                ('validation_url', models.URLField(blank=True)),
                ('result_url', models.URLField(blank=True)),
                ('auto_reconcile', models.BooleanField(default=True)),
                ('auto_send_stk', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_config', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_phone', models.CharField(db_index=True, max_length=20)),
                ('business_shortcode', models.CharField(max_length=20)),
                ('account_reference', models.CharField(blank=True, db_index=True, max_length=50)),
                ('transaction_date', models.DateTimeField()),
                ('payment_method', models.CharField(default='MPESA', max_length=20)),
                ('receipt_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='PENDING', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('invoice_reference', models.CharField(blank=True, db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_transactions', to='core.company')),
            ],
            options={
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['transaction_id'], name='mpesa_mpesa_transac_bfb356_idx'), models.Index(fields=['customer_phone'], name='mpesa_mpesa_custome_758d26_idx'), models.Index(fields=['account_reference'], name='mpesa_mpesa_account_20654c_idx'), models.Index(fields=['status'], name='mpesa_mpesa_status_b7937d_idx')],
            },
        ),
    ]
