# Generated by Django 4.2.9 on 2026-05-22 10:44

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=30)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('kra_pin', models.CharField(blank=True, max_length=20)),
                ('nssf_number', models.CharField(blank=True, max_length=30)),
                ('nhif_number', models.CharField(blank=True, max_length=30)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('bank_account', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.company')),
            ],
            options={
                'ordering': ['full_name'],
                'unique_together': {('company', 'employee_number')},
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.PositiveSmallIntegerField()),
                ('period_year', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processed', 'Processed'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('total_gross', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_net', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='core.company')),
            ],
            options={
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('company', 'period_month', 'period_year')},
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross', models.DecimalField(decimal_places=2, max_digits=14)),
                ('nssf', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('nhif', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('paye', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('net', models.DecimalField(decimal_places=2, max_digits=14)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='payroll.employee')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollrun')),
            ],
            options={
                'unique_together': {('run', 'employee')},
            },
        ),
    ]
