# Generated by Django 4.2.9 on 2026-06-15 08:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KRAVATReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('sales_vat_declared', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('purchases_vat_declared', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_vat_declared', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('acknowledgement_receipt', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='KRATaxpayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pin', models.CharField(max_length=50)),
                ('taxpayer_name', models.CharField(max_length=255)),
                ('is_vat_registered', models.BooleanField(default=False)),
                ('vat_registration_date', models.DateField(blank=True, null=True)),
                ('is_withholding_tax_agent', models.BooleanField(default=False)),
                ('withholding_tax_agent_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kra_profile', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='KRAPinValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pin_validated', models.CharField(max_length=50)),
                ('is_valid', models.BooleanField(default=False)),
                ('taxpayer_name', models.CharField(blank=True, max_length=255)),
                ('response_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='KRAeTIMSInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50)),
                ('etims_invoice_number', models.CharField(max_length=100, unique=True)),
                ('qr_code', models.TextField(blank=True)),
                ('status', models.CharField(default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
        ),
    ]
